- app/Http/Controllers/AuthController.php
- composer.lock
- public/css/form.css
- resources/views/auth/compte.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
rendu la page de modifications du compte accessible et fonctionnelle
> ajouté page compte pour modif les info du compte

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/UserController.php
- app/Http/Middleware/Authenticate.php
- app/Http/Requests/UserStoreRequest.php
- resources/views/user/compte.blade.php
- resources/views/user/creation.blade.php
- resources/views/welcome.blade.php
- routes/web.php
Terminé les vues méthodes concernant le user basic, login logout, modif compte, ajout compte
> Fp modif compte

- retroactionSprint1.md
> Rétroaction du sprint 1 rédigé et corrigé

- app/Http/Controllers/BouteilleController.php
- app/Http/Requests/StoreBouteilleRequest.php
- app/Http/Requests/UpdateBouteilleRequest.php
- app/Models/Bouteille.php
- composer.lock
- routes/api.php
#38 
terminé et testé. beaucoup appris, le reste devrais aller plus vite
> Fp bouteille api

- app/Http/Controllers/BouteilleController.php
- app/Http/Controllers/CellierController.php
- app/Services/BouteilleQuery.php
- routes/api.php
> implementation du search et des sort dans l'url de l'api

- app/Models/Bouteille.php
> retouche: relation:bouteille hasmany note_commentaire

- app/Models/Note_Commentaire.php
> relation: note_commentaire belongTo bouteille

- database/migrations/2023_05_04_191620_create_cellier__bouteilles_table.php
> migration cellier_bouteilles

- routes/api.php
> proteger les routes avec auth:sanctum

- app/Http/Controllers/BouteilleController.php
- app/Http/Controllers/CellierController.php
- app/Http/Requests/StoreCellierRequest.php
- app/Http/Requests/UpdateBouteilleRequest.php
- app/Http/Requests/UpdateCellierRequest.php
- app/Services/CellierQuery.php
> debut api celliers et [eq] pour query dans l'url

- routes/web.php
> correction web.php

- app/Models/Bouteille.php
> ajout de note_commentaire au modèle bouteille

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/UserController.php
- app/Models/User.php
- routes/api.php
> basic crud terminé pour users

- app/Http/Controllers/CellierBouteilleController.php
- app/Http/Requests/UpdateCellierBouteilleRequest.php
- app/Http/Resources/PastilleCouleurResource.php
- app/Models/Cellier_Bouteille.php
- app/Models/Pastille_Couleur.php
> Fp cellier bouteille crud

- app/Http/Controllers/AdminController.php
> nouvelle bouteille importer de la saq manquait actif a true pour etre affichées

- app/Http/Controllers/BouteilleController.php
- app/Services/BouteilleQuery.php
> bouteilles sort fonctionnel

- app/Http/Controllers/CellierBouteilleController.php
Ajustement de la quantité suite a l'entrée d'un doublon dans la db
> Fp doublons bouteille cellier

- app/Http/Controllers/AuthController.php
- app/Http/Requests/LoginUserRequest.php
- app/Http/Requests/RegisterUserRequest.php
- public/crawler.php
- routes/api.php
> Création du Login

- app/Http/Controllers/AuthController.php
- routes/api.php
> ajout du register après avoir été testé dans postman

- Retroactions.md
- app/Http/Controllers/AuthController.php
- routes/api.php
> Identification

- app/Http/Controllers/BouteilleController.php
- app/Http/Resources/BouteilleResource.php
- app/Http/Resources/CellierBouteilleResource.php
- app/Http/Resources/NoteCommentaireResource.php
- app/Models/Bouteille.php
- app/Models/Cellier_Bouteille.php
- app/Models/Note_Commentaire.php
- database/migrations/2023_05_04_191025_create_note__commentaires_table.php
- database/migrations/2023_05_04_191620_create_cellier__bouteilles_table.php
> Fp notes commentaires

- app/Http/Controllers/AuthController.php
- app/Http/Controllers/BouteilleController.php
- app/Http/Controllers/CellierBouteilleController.php
> Fp hotfix general

- app/Http/Controllers/BouteilleController.php
- app/Http/Controllers/CellierBouteilleController.php
- app/Http/Controllers/CellierController.php
- app/Http/Controllers/ErreurController.php
- app/Http/Controllers/NoteCommentaireController.php
- app/Http/Controllers/PastilleCouleurController.php
- app/Http/Controllers/PaysController.php
- app/Http/Controllers/TypeController.php
- app/Http/Controllers/UserController.php
- app/Http/Controllers/UtilisateurController.php
- routes/api.php
Tout est en try catch et je considère l'api dans sa version finale
#36
> Fp cleanup
